disabled_rules:
   - line_length
   - trailing_whitespace
   - function_parameter_count
   - vertical_whitespace
   - weak_delegate
   - multiple_closures_with_trailing_closure
   - class_delegate_protocol
   - valid_ibinspectable
   - implicit_getter
excluded:
  - Pods
file_length:
    warning: 750
    error: 1000
line_length:
    warning: 500
    error: 700
function_body_length:
    warning: 500
    error: 700
identifier_name:
    min_length: 3
    max_length:
        warning: 90
        error: 1000
    excluded:
        - id
        - i
        - vc
        - ip
type_body_length:
    warning: 500
    error: 750
large_tuple:
    warning: 5
    error: 7
type_name:
    min_length: 3
    max_length:
        warning: 75
        error: 100
